# .github/workflows/docs.yml
name: Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Add these permissions at the top level of your workflow
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Generate documentation
        run: |
          python src/visualization_generator.py
          cp docs/index.html docs/README.md
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true